# Application Configuration Example
# Copy this file to config.yaml and modify as needed

# Application environment: development, testing, or production
environment: production

# Path to the SQLite database file
database_path: downloads.db

# Server configuration
server:
  # Host to bind the server to (0.0.0.0 for all interfaces)
  host: 0.0.0.0
  # Port to listen on
  port: 54759

# Daemon configuration
daemon:
  # Number of concurrent downloads
  concurrency: 3
  # Time to keep downloads before automatic cleanup (format: 1d, 2h, 30m)
  expire_downloads: 1d


  # URL mappers for premium download services
  # Format: domain: command
  # mapper:
  #   rapidgator.net: python3 ~/cli_scripts/debrid_api.py

  # Directory for temporary downloads
  # temporary_download_directory: <dir>

  # Path to the folder creator script
  # The specified command is passed the directory where downloaded (and unpacked) files
  # are stored. Based on patterns, user can create folders as they want.
  # The newly created folders are then moved to the final directory (regardless of a temporary directory).
  # If the script returns non-zero exit code, move task will still occur
  # organize: python3 ~/cli_scripts/folder_creator.py

  # optionst to aria2 downloader
  aria2:
    log: /tmp/aria2.log
    download_options:
      max-connection-per-server: 1
      # For some reason, this is not working but api call succeeds. However, falloc = "abc" fails
      # auto-save-interval: 0  # no control file
      file-allocation: falloc
      content-disposition-default-utf8: true


# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  # Log format
  format: "%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - %(message)s"
  # Date format in logs
  date_format: "%Y-%m-%d %H:%M:%S"
